# Copyright (c) 2018 Amdocs, Bell Canada
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# File generated from /opt/config
#
GLOBAL_INJECTED_AAF_IP_ADDR = "aaf-service.onap"
GLOBAL_INJECTED_AAI1_IP_ADDR = "aai.onap"
GLOBAL_INJECTED_AAI2_IP_ADDR = "N/A"
GLOBAL_INJECTED_APPC_IP_ADDR = "appc.onap"
GLOBAL_INJECTED_APPC_CDT_IP_ADDR = "appc-cdt.onap"
GLOBAL_INJECTED_ARTIFACTS_VERSION = "1.3.0"
GLOBAL_INJECTED_CLAMP_IP_ADDR = "clamp.onap"
GLOBAL_INJECTED_CLI_IP_ADDR = "cli.onap"
GLOBAL_INJECTED_CLOUD_ENV = "openstack"
GLOBAL_INJECTED_DCAE_IP_ADDR = "dcae-healthcheck.onap"
GLOBAL_INJECTED_DMAAP_DR_PROV_IP_ADDR = "dmaap-dr-prov.onap"
GLOBAL_INJECTED_DMAAP_DR_NODE_IP_ADDR = "dmaap-dr-node.onap"
GLOBAL_INJECTED_DNS_IP_ADDR = "N/A"
GLOBAL_INJECTED_DOCKER_VERSION = "1.2-STAGING-latest"
GLOBAL_INJECTED_EXTERNAL_DNS = "N/A"
GLOBAL_INJECTED_LOG_ELASTICSEARCH_IP_ADDR = "log-es.onap"
GLOBAL_INJECTED_LOG_KIBANA_IP_ADDR = "log-kibana.onap"
GLOBAL_INJECTED_LOG_LOGSTASH_IP_ADDR = "log-ls-http.onap"
GLOBAL_INJECTED_POMBA_AAI_CONTEXT_BUILDER_IP_ADDR = "pomba-aaictxbuilder.onap"
GLOBAL_INJECTED_POMBA_SDC_CONTEXT_BUILDER_IP_ADDR = "pomba-sdcctxbuilder.onap"
GLOBAL_INJECTED_POMBA_NETWORK_DISC_CONTEXT_BUILDER_IP_ADDR = "pomba-networkdiscoveryctxbuilder.onap"
GLOBAL_INJECTED_POMBA_SERVICE_DECOMPOSITION_IP_ADDR = "pomba-servicedecomposition.onap"
GLOBAL_INJECTED_POMBA_SDNC_CTX_BUILDER_IP_ADDR = "pomba-sdncctxbuilder.onap"
GLOBAL_INJECTED_POMBA_NETWORKDISCOVERY_MICROSERVICE_IP_ADDR = "pomba-networkdiscovery.onap"
GLOBAL_INJECTED_POMBA_VALIDATION_SERVICE_IP_ADDR = "pomba-validation-service.onap"
GLOBAL_INJECTED_POMBA_KIBANA_IP_ADDR = "pomba-kibana.onap"
GLOBAL_INJECTED_POMBA_ELASTIC_SEARCH_IP_ADDR = "pomba-es.onap"
GLOBAL_INJECTED_POMBA_CONTEX_TAGGREGATOR_IP_ADDR = "pomba-contextaggregator.onap"
GLOBAL_INJECTED_KEYSTONE = "http://10.12.25.2:5000"
GLOBAL_INJECTED_MR_IP_ADDR = "message-router.onap"
GLOBAL_INJECTED_BC_IP_ADDR = "dmaap-bc.onap"
GLOBAL_INJECTED_MUSIC_IP_ADDR = "music.onap"
GLOBAL_INJECTED_NBI_IP_ADDR = "nbi.onap"
GLOBAL_INJECTED_NETWORK = "oam_network_sSXO"
GLOBAL_INJECTED_NEXUS_DOCKER_REPO = "nexus3.onap.org:10001"
GLOBAL_INJECTED_NEXUS_PASSWORD = "docker"
GLOBAL_INJECTED_NEXUS_REPO = "https://nexus.onap.org/content/sites/raw"
GLOBAL_INJECTED_NEXUS_USERNAME = "docker"
GLOBAL_INJECTED_OOF_IP_ADDR = "N/A"
GLOBAL_INJECTED_OOF_HOMING_IP_ADDR = "oof-has-api.onap"
GLOBAL_INJECTED_OOF_SNIRO_IP_ADDR = "oof-osdf.onap"
GLOBAL_INJECTED_OOF_CMSO_IP_ADDR = "oof-cmso.onap"
GLOBAL_INJECTED_MSB_IP_ADDR = "msb-iag.onap"
GLOBAL_INJECTED_OPENSTACK_API_KEY = "bbaef6cd76625ab9eb60deedeae7dbb9"
GLOBAL_INJECTED_OPENSTACK_PASSWORD = "tenantPassword"
GLOBAL_INJECTED_OPENSTACK_TENANT_ID = "3583253e932845a09cd4c8ca2f31d095"
GLOBAL_INJECTED_OPENSTACK_USERNAME = "demo"
GLOBAL_INJECTED_OPENSTACK_PROJECT_NAME = "onap"
GLOBAL_INJECTED_OPENSTACK_DOMAIN_ID = "default"
GLOBAL_INJECTED_OPENSTACK_KEYSTONE_API_VERSION = "v2.0"

GLOBAL_INJECTED_REGION_THREE = "RegionThree"
GLOBAL_INJECTED_KEYSTONE_REGION_THREE = "http://10.12.25.2:5000"
GLOBAL_INJECTED_OPENSTACK_KEYSTONE_API_VERSION_REGION_THREE = "v3"
GLOBAL_INJECTED_OPENSTACK_USERNAME_REGION_THREE = "demo"
GLOBAL_INJECTED_OPENSTACK_MSO_ENCRYPTED_PASSWORD_REGION_THREE  = "4C40E5362BF66194152B2BB48BC5A9700DA2BF4018631CE709366C1459BCCD779C7BCC1A"
GLOBAL_INJECTED_OPENSTACK_TENANT_ID_REGION_THREE = "3583253e932845a09cd4c8ca2f31d095"
GLOBAL_INJECTED_OPENSTACK_PROJECT_DOMAIN__REGION_THREE = "Integration-HEAT-Staging-Daily"
GLOBAL_INJECTED_OPENSTACK_USER_DOMAIN__REGION_THREE = "Default"

GLOBAL_INJECTED_POLICY_IP_ADDR = "pdp.onap"
GLOBAL_INJECTED_POLICY_HEALTHCHECK_IP_ADDR = "drools.onap"
GLOBAL_INJECTED_PORTAL_IP_ADDR = "portal-app.onap"
GLOBAL_INJECTED_PUBLIC_NET_ID = "971040b2-7059-49dc-b220-4fab50cb2ad4"
GLOBAL_INJECTED_REGION = "RegionThree"
GLOBAL_INJECTED_SCRIPT_VERSION = "1.3.0"
GLOBAL_INJECTED_SDC_BE_IP_ADDR = "sdc-be.onap"
GLOBAL_INJECTED_SDC_BE_ONBOARD_IP_ADDR = "sdc-onboarding-be.onap"
GLOBAL_INJECTED_SDC_FE_IP_ADDR = "sdc-fe.onap"
GLOBAL_INJECTED_SDC_IP_ADDR = "N/A"
GLOBAL_INJECTED_SDNC_IP_ADDR = "sdnc.onap"
GLOBAL_INJECTED_SDNC_PORTAL_IP_ADDR = "sdnc-portal.onap"
GLOBAL_INJECTED_SO_APIHAND_IP_ADDR = "so.onap"
GLOBAL_INJECTED_SO_ASDCHAND_IP_ADDR = "so-sdc-controller.onap"
GLOBAL_INJECTED_SO_BPMN_IP_ADDR = "so-bpmn-infra.onap"
GLOBAL_INJECTED_SO_CATDB_IP_ADDR = "so-catalog-db-adapter.onap"
GLOBAL_INJECTED_SO_IP_ADDR = "so.onap"
GLOBAL_INJECTED_SO_OPENSTACK_IP_ADDR = "so-openstack-adapter.onap"
GLOBAL_INJECTED_SO_REQDB_IP_ADDR = "so-request-db-adapter.onap"
GLOBAL_INJECTED_SO_SDNC_IP_ADDR = "so-sdnc-adapter.onap"
GLOBAL_INJECTED_SO_VFC_IP_ADDR = "so-vfc-adapter.onap"
GLOBAL_INJECTED_SO_VNFM_IP_ADDR = "so-vnfm-adapter.onap"
GLOBAL_INJECTED_UBUNTU_1404_IMAGE = "ubuntu-14-04-cloud-amd64"
GLOBAL_INJECTED_UBUNTU_1604_IMAGE = "ubuntu-16-04-cloud-amd64"
GLOBAL_INJECTED_VM_IMAGE_NAME = "ubuntu-14-04-cloud-amd64"
GLOBAL_INJECTED_VID_IP_ADDR = "vid.onap"
GLOBAL_INJECTED_VM_FLAVOR = "m1.medium"
GLOBAL_INJECTED_VNFSDK_IP_ADDR = "refrepo.onap"

GLOBAL_INJECTED_PROPERTIES = {
    "GLOBAL_INJECTED_AAF_IP_ADDR" : "aaf-service.onap",
    "GLOBAL_INJECTED_AAI1_IP_ADDR" : "aai.onap",
    "GLOBAL_INJECTED_AAI2_IP_ADDR" : "N/A",
    "GLOBAL_INJECTED_APPC_IP_ADDR" : "appc.onap",
    "GLOBAL_INJECTED_APPC_CDT_IP_ADDR" : "appc-cdt.onap",
    "GLOBAL_INJECTED_ARTIFACTS_VERSION" : "1.3.0",
    "GLOBAL_INJECTED_CLAMP_IP_ADDR" : "clamp.onap",
    "GLOBAL_INJECTED_CLI_IP_ADDR" : "cli.onap",
    "GLOBAL_INJECTED_CLOUD_ENV" : "openstack",
    "GLOBAL_INJECTED_DCAE_IP_ADDR" : "dcae-healthcheck.onap",
    "GLOBAL_INJECTED_DMAAP_DR_PROV_IP_ADDR" : "dmaap-dr-prov.onap",
    "GLOBAL_INJECTED_DMAAP_DR_NODE_IP_ADDR" : "dmaap-dr-node.onap",
    "GLOBAL_INJECTED_DNS_IP_ADDR" : "N/A",
    "GLOBAL_INJECTED_DOCKER_VERSION" : "1.2-STAGING-latest",
    "GLOBAL_INJECTED_EXTERNAL_DNS" : "N/A",
    "GLOBAL_INJECTED_KEYSTONE" : "http://10.12.25.2:5000",
    "GLOBAL_INJECTED_LOG_ELASTICSEARCH_IP_ADDR" : "log-es.onap",
    "GLOBAL_INJECTED_LOG_KIBANA_IP_ADDR" : "log-kibana.onap",
    "GLOBAL_INJECTED_LOG_LOGSTASH_IP_ADDR" : "log-ls.onap",
    "GLOBAL_INJECTED_MR_IP_ADDR" : "message-router.onap",
    "GLOBAL_INJECTED_BC_IP_ADDR" : "dmaap-bc.onap",
    "GLOBAL_INJECTED_POMBA_AAI_CONTEXT_BUILDER_IP_ADDR" : "pomba-aaictxbuilder.onap",
    "GLOBAL_INJECTED_POMBA_SDC_CONTEXT_BUILDER_IP_ADDR" : "pomba-sdcctxbuilder.onap",
    "GLOBAL_INJECTED_POMBA_NETWORK_DISC_CONTEXT_BUILDER_IP_ADDR" : "pomba-networkdiscovery.onap",
    "GLOBAL_INJECTED_POMBA_SERVICE_DECOMPOSITION_IP_ADDR" : "pomba-servicedecomposition.onap",
    "GLOBAL_INJECTED_POMBA_SDNC_CTX_BUILDER_IP_ADDR" : "pomba-sdncctxbuilder.onap",
    "GLOBAL_INJECTED_POMBA_CONTEX_TAGGREGATOR_IP_ADDR" : "pomba-contextaggregator.onap",
    "GLOBAL_INJECTED_MUSIC_IP_ADDR" : "music.onap",
    "GLOBAL_INJECTED_NBI_IP_ADDR" : "nbi.onap",
    "GLOBAL_INJECTED_NETWORK" : "oam_network_sSXO",
    "GLOBAL_INJECTED_NEXUS_DOCKER_REPO" : "nexus3.onap.org:10001",
    "GLOBAL_INJECTED_NEXUS_PASSWORD" : "docker",
    "GLOBAL_INJECTED_NEXUS_REPO" : "https://nexus.onap.org/content/sites/raw",
    "GLOBAL_INJECTED_NEXUS_USERNAME" : "docker",
    "GLOBAL_INJECTED_OOF_IP_ADDR" : "N/A",
    "GLOBAL_INJECTED_OOF_HOMING_IP_ADDR" : "oof-has-api.onap",
    "GLOBAL_INJECTED_OOF_SNIRO_IP_ADDR" : "oof-osdf.onap",
    "GLOBAL_INJECTED_OOF_CMSO_IP_ADDR" : "oof-cmso.onap",
    "GLOBAL_INJECTED_MSB_IP_ADDR" : "msb-iag.onap",
    "GLOBAL_INJECTED_OPENSTACK_API_KEY" : "bbaef6cd76625ab9eb60deedeae7dbb9",
    "GLOBAL_INJECTED_OPENSTACK_PASSWORD" : "tenantPassword",
    "GLOBAL_INJECTED_OPENSTACK_TENANT_ID" : "3583253e932845a09cd4c8ca2f31d095",
    "GLOBAL_INJECTED_OPENSTACK_USERNAME" : "demo",
    "GLOBAL_INJECTED_OPENSTACK_PROJECT_NAME" : "onap",
    "GLOBAL_INJECTED_OPENSTACK_DOMAIN_ID" : "default",
    "GLOBAL_INJECTED_OPENSTACK_KEYSTONE_API_VERSION" : "v2.0",
    "GLOBAL_INJECTED_REGION_THREE" : "RegionThree",
    "GLOBAL_INJECTED_KEYSTONE_REGION_THREE" : "http://10.12.25.2:5000",
    "GLOBAL_INJECTED_OPENSTACK_KEYSTONE_API_VERSION_REGION_THREE" : "v3",
    "GLOBAL_INJECTED_OPENSTACK_USERNAME_REGION_THREE" : "demo",
    "GLOBAL_INJECTED_OPENSTACK_MSO_ENCRYPTED_PASSWORD_REGION_THREE" : "4C40E5362BF66194152B2BB48BC5A9700DA2BF4018631CE709366C1459BCCD779C7BCC1A",
    "GLOBAL_INJECTED_OPENSTACK_TENANT_ID_REGION_THREE" : "3583253e932845a09cd4c8ca2f31d095",
    "GLOBAL_INJECTED_OPENSTACK_PROJECT_DOMAIN__REGION_THREE" : "Integration-HEAT-Staging-Daily",
    "GLOBAL_INJECTED_OPENSTACK_USER_DOMAIN__REGION_THREE" : "Default",
    "GLOBAL_INJECTED_POLICY_IP_ADDR" : "pdp.onap",
    "GLOBAL_INJECTED_POLICY_HEALTHCHECK_IP_ADDR" : "drools.onap",
    "GLOBAL_INJECTED_PORTAL_IP_ADDR" : "portal-app.onap",
    "GLOBAL_INJECTED_PUBLIC_NET_ID" : "971040b2-7059-49dc-b220-4fab50cb2ad4",
    "GLOBAL_INJECTED_REGION" : "RegionThree",
    "GLOBAL_INJECTED_SDC_BE_IP_ADDR" : "sdc-be.onap",
    "GLOBAL_INJECTED_SDC_BE_ONBOARD_IP_ADDR" : "sdc-onboarding-be.onap",
    "GLOBAL_INJECTED_SDC_FE_IP_ADDR" : "sdc-fe.onap",
    "GLOBAL_INJECTED_SDC_IP_ADDR" : "N/A",
    "GLOBAL_INJECTED_SCRIPT_VERSION" : "1.3.0",
    "GLOBAL_INJECTED_SDNC_IP_ADDR" : "sdnc.onap",
    "GLOBAL_INJECTED_SDNC_PORTAL_IP_ADDR" : "sdnc-portal.onap",
    "GLOBAL_INJECTED_SO_APIHAND_IP_ADDR" : "so.onap",
    "GLOBAL_INJECTED_SO_ASDCHAND_IP_ADDR" : "so-sdc-controller.onap",
    "GLOBAL_INJECTED_SO_BPMN_IP_ADDR" : "so-bpmn-infra.onap",
    "GLOBAL_INJECTED_SO_CATDB_IP_ADDR" : "so-catalog-db-adapter.onap",
    "GLOBAL_INJECTED_SO_IP_ADDR" : "so.onap",
    "GLOBAL_INJECTED_SO_OPENSTACK_IP_ADDR" : "so-openstack-adapter.onap",
    "GLOBAL_INJECTED_SO_REQDB_IP_ADDR" : "so-request-db-adapter.onap",
    "GLOBAL_INJECTED_SO_SDNC_IP_ADDR" : "so-sdnc-adapter.onap",
    "GLOBAL_INJECTED_SO_VFC_IP_ADDR" : "so-vfc-adapter.onap",
    "GLOBAL_INJECTED_SO_VNFM_IP_ADDR" : "so-vnfm-adapter.onap",
    "GLOBAL_INJECTED_UBUNTU_1404_IMAGE" : "ubuntu-14-04-cloud-amd64",
    "GLOBAL_INJECTED_UBUNTU_1604_IMAGE" : "ubuntu-16-04-cloud-amd64",
    "GLOBAL_INJECTED_VM_IMAGE_NAME" : "ubuntu-14-04-cloud-amd64",
    "GLOBAL_INJECTED_VID_IP_ADDR" : "vid.onap",
    "GLOBAL_INJECTED_VM_FLAVOR" : "m1.medium",
    "GLOBAL_INJECTED_VNFSDK_IP_ADDR" : "refrepo.onap"

}
