apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pmhttpsserver.fullname" . }}
  namespace: { { .Values.namespace } }
  labels:
    {{- include "pmhttpsserver.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pmhttpsserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "pmhttpsserver.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "repositoryGenerator.repository" . }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: http2
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: certstore
              mountPath: {{ .Values.certsDir }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: certstore
          secret:
            secretName: {{.Values.certificates.secretName}}
            defaultMode: 0400
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
