apiVersion: v1
kind: Service
metadata:
  name: {{ include "pmhttpsserver.fullname" . }}
  namespace: {{ include "pmhttpsserver.namespace" . }}
  labels:
    {{- include "pmhttpsserver.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 8080
      targetPort: http2
      protocol: TCP
      name: http2
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "pmhttpsserver.selectorLabels" . | nindent 4 }}
