apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: '{{ include "ves-client.fullname" . }}-cert'
  namespace: {{ include "ves-client.namespace" . }}
spec:
  secretName: ves-client-secret-cmpv2
  commonName: {{ include "ves-client.fullname" . }}
  renewBefore: {{ .Values.certificates.renewBefore }}
  duration: {{ .Values.certificates.duration }}
  subject:
    organizations:
      - {{ .Values.certificates.subject.organization }}
    countries:
      - {{ .Values.certificates.subject.country }}
    localities:
      - {{ .Values.certificates.subject.locality }}
    provinces:
      - {{ .Values.certificates.subject.province }}
    organizationalUnits:
      - {{ .Values.certificates.subject.organizationalUnit }}
  issuerRef:
    group: {{ .Values.certificates.issuerRef.group }}
    kind: {{ .Values.certificates.issuerRef.kind }}
    name: {{ .Values.certificates.issuerRef.name }}
  dnsNames: {{ include "ves-client.dnsNames" . | indent 4 }}
  keystores:
    {{ toYaml .Values.certificates.keystores | nindent 4 }}
